name: Deploy and Run Telegram Bot # 工作流程的名稱，方便您識別

on:
  # 此工作流程會在每次有新的提交（push）到 `main` 分支時觸發
  push:
    branches:
      - main

jobs:
  run_bot:
    # 執行此任務的環境，這裡使用最新的 Ubuntu 虛擬機
    runs-on: ubuntu-latest
    
    steps:
      # 第一步：檢查（checkout）您的儲存庫程式碼到虛擬機上
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 第二步：設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 指定您使用的 Python 版本

      # 第三步：安裝依賴套件
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 第四步：運行您的 Python 機器人
      - name: Run Telegram Bot
        # 使用 env 關鍵字將 GitHub Secret 作為環境變數傳遞給程式碼
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python vx_twitter_bot.py
